BinhTung/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BinhTung.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Display(Name = "Tên sản phẩm", Description = "Tên sản phẩm dài tối đa 150 ký tự"),
         Required(ErrorMessage = "Hãy nhập Tên sản phẩm"), StringLength(150, ErrorMessage = "Tối đa 150 ký tự"),
         UIHint("TextBox")]
        public string Name { get; set; }
        [Display(Name = "Thông tin sản phẩm"), Required(ErrorMessage = "Thông tin sản phẩm"),
         StringLength(600, ErrorMessage = "Tối đa 600 ký tự"), DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Display(Name = "Mô tả chi tiết"), UIHint("EditorBox")]
        public string Body { get; set; }
        [Display(Name = "Danh sách ảnh"), UIHint("UploadMultiFile")]
        public string ListImage { get; set; }
        [Display(Name = "Số lượng"), Required(ErrorMessage = "Hãy nhập số lượng"), RegularExpression(@"\d+", ErrorMessage = "Nhập số nguyên dương"), UIHint("NumberBox")]
        public int Quantity { get; set; }
        [Display(Name = "Giá gốc"), DisplayFormat(DataFormatString = "{0:N0}đ")]
        public decimal? Price { get; set; }
        [Display(Name = "Giảm giá"), DisplayFormat(DataFormatString = "{0:N0}đ")]
        public decimal? SaleOff { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        [Display(Name = "Ngày đăng")]
        public DateTime CreateDate { get; set; }
        public int View { get; set; }
        [Display(Name = "Thứ tự"), Required(ErrorMessage = "Hãy nhập số thứ tự"), RegularExpression(@"\d+", ErrorMessage = "Chỉ nhập số nguyên dương"), UIHint("NumberBox")]
        public int Sort { get; set; }
        [Display(Name = "Danh mục sản phẩm"), Required(ErrorMessage = "Hãy chọn danh mục sản phẩm")]
        public int ProductCategoryId { get; set; }
        [Display(Name = "Hiện nổi bật")]
        public bool Hot { get; set; }
        [Display(Name = "Hoạt động")]
        public bool Active { get; set; }
        [Display(Name = "Hiện trang chủ")]
        public bool Home { get; set; }
        [StringLength(300)]
        public string Url { get; set; }
        [Display(Name = "Thẻ tiêu đề"), StringLength(100, ErrorMessage = "Tối đa 100 ký tự"), UIHint("TextBox")]
        public string TitleMeta { get; set; }
        [Display(Name = "Thẻ mô tả"), StringLength(500, ErrorMessage = "Tối đa 500 ký tự"), UIHint("TextArea")]
        public string DescriptionMeta { get; set; }
        [Display(Name = "Loại sản phẩm")]
        public virtual ProductCategory ProductCategory { get; set; }

        public Product()
        {
            CreateDate = DateTime.Now;
            Active = true;
            View = 1;
        }
    }
}

BinhTung/Models/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BinhTung.Models
{
    public class ProductCategory
    {
        public int Id { get; set; }
        [Display(Name = "Tên danh mục"), Required(ErrorMessage = "Hãy nhập tên danh mục"), StringLength(80, ErrorMessage = "Tối đa 80 ký tự"), UIHint("TextBox")]
        public string CategoryName { get; set; }
        [Display(Name = "Đường dẫn"), StringLength(500, ErrorMessage = "Tối đa 500 ký tự"), UIHint("TextBox")]
        public string Url { get; set; }
        [Display(Name = "Thứ tự"), Required(ErrorMessage = "Hãy nhập số thứ tự"), RegularExpression(@"\d+", ErrorMessage = "Chỉ nhập số nguyên dương"), UIHint("NumberBox")]
        public int CategorySort { get; set; }
        [Display(Name = "Hoạt động")]
        public bool CategoryActive { get; set; }
        [Display(Name = "Danh mục cha")]
        public int? ParentId { get; set; }
        [Display(Name = "Hiển thị trang chủ")]
        public bool ShowHome { get; set; }
        [Display(Name = "Hiển thị chân trang")]
        public bool ShowFooter { get; set; }
        [Display(Name = "Đặc biệt")]
        public bool Special { get; set; }
        [Display(Name = "Thẻ tiêu đề"), StringLength(100, ErrorMessage = "Tối đa 100 ký tự"), UIHint("TextBox")]
        public string TitleMeta { get; set; }
        [Display(Name = "Thẻ mô tả"), StringLength(500, ErrorMessage = "Tối đa 500 ký tự"), UIHint("TextArea")]
        public string DescriptionMeta { get; set; }
        [Display(Name = "Giới thiệu ngắn"), StringLength(500, ErrorMessage = "Tối đa 500 ký tự"), UIHint("TextArea")]
        public string Description { get; set; }
        [Display(Name = "Ảnh đại diện"), StringLength(500), UIHint("ImageProductCat")]
        public string Image { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public ProductCategory()
        {
            ShowHome = false;
            CategoryActive = true;
        }
    }
}

BinhTung/Controllers/ProductVcmsController.cs
using BinhTung.DAL;
using BinhTung.Models;
using BinhTung.ViewModel;
using Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BinhTung.Controllers
{
    [Authorize]
    public class ProductVcmsController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        private IEnumerable<ProductCategory> ProductCategories => _unitOfWork.ProCategoryRepository.Get(a => a.CategoryActive, q => q.OrderBy(a => a.CategorySort));
        private SelectList ParentProductCategoryList => new SelectList(ProductCategories.Where(a => a.ParentId == null), "Id", "CategoryName");

        #region ProductCategory
        [ChildActionOnly]
        public ActionResult ListCategory()
        {
            var allcats = _unitOfWork.ProCategoryRepository.Get(orderBy: q => q.OrderBy(a => a.CategorySort));
            return PartialView(allcats);
        }
        public ActionResult ProductCategory(string result = "")
        {
            ViewBag.ArticleCat = result;
            ViewBag.RootCats =
                new SelectList(ProductCategories.Where(a => a.ParentId == null), "Id", "CategoryName");
            return View(new ProductCategory());
        }
        [HttpPost]
        public ActionResult ProductCategory(ProductCategory category, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;
                var file = Request.Files["Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (file.ContentType != "image/jpeg" & file.ContentType != "image/png" && file.ContentType != "image/gif")
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 4000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 4MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/productCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = DateTime.Now.ToFileTimeUtc() + Path.GetExtension(file.FileName);

                            category.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                            var newImage = Image.FromStream(file.InputStream);
                            //var fixSizeImage = HtmlHelpers.FixedSize(newImage, 600, 600, false);
                            //HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }
                if (isPost)
                {
                    category.Url = HtmlHelpers.ConvertToUnSign(null, category.Url ?? category.CategoryName);
                    _unitOfWork.ProCategoryRepository.Insert(category);
                    _unitOfWork.Save();
                    return RedirectToAction("ProductCategory", new { result = "success" });
                }
            }
            ViewBag.RootCats = new SelectList(ProductCategories.Where(a => a.ParentId == null), "Id", "CategoryName");
            return View(category);
        }
        public ActionResult UpdateCategory(int catId = 0)
        {
            var category = _unitOfWork.ProCategoryRepository.GetById(catId);
            if (category == null)
            {
                return RedirectToAction("ProductCategory");
            }
            ViewBag.RootCats = new SelectList(ProductCategories.Where(a => a.ParentId == null), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost]
        public ActionResult UpdateCategory(ProductCategory category, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;
                var file = Request.Files["Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (file.ContentType != "image/jpeg" & file.ContentType != "image/png" && file.ContentType != "image/gif")
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 4000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 4MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/productCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = DateTime.Now.ToFileTimeUtc() + Path.GetExtension(file.FileName);

                            if (System.IO.File.Exists(Server.MapPath("/images/productCategory/" + category.Image)))
                            {
                                System.IO.File.Delete(Server.MapPath("/images/productCategory/" + category.Image));
                            }
                            category.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                            var newImage = Image.FromStream(file.InputStream);
                            //var fixSizeImage = HtmlHelpers.FixedSize(newImage, 600, 600, false);
                            //HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }
                else
                {
                    category.Image = fc["CurrentFile"];
                }
                if (isPost)
                {
                    category.Url = HtmlHelpers.ConvertToUnSign(null, category.Url ?? category.CategoryName);
                    _unitOfWork.ProCategoryRepository.Update(category);
                    _unitOfWork.Save();
                    return RedirectToAction("ProductCategory", new { result = "update" });
                }
            }
            ViewBag.RootCats = new SelectList(ProductCategories.Where(a => a.ParentId == null), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost]
        public bool DeleteCategory(int catId = 0)
        {
            var category = _unitOfWork.ProCategoryRepository.GetById(catId);
            if (category == null)
            {
                return false;
            }
            _unitOfWork.ProCategoryRepository.Delete(category);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateProductCat(int sort = 1, bool active = false, bool special = false, bool home = false, bool footer = false, int productCatId = 0)
        {
            var productCat = _unitOfWork.ProCategoryRepository.GetById(productCatId);
            if (productCat == null)
            {
                return false;
            }
            productCat.CategorySort = sort;
            productCat.CategoryActive = active;
            productCat.Special = special;
            productCat.ShowHome = home;
            productCat.ShowFooter = footer;

            _unitOfWork.Save();
            return true;
        }
        #endregion

        #region Product
        public ActionResult ListProduct(int? page, string name, int? parentId, int catId = 0, string sort = "date-desc", string result = "")
        {
            ViewBag.Result = result;
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var products = _unitOfWork.ProductRepository.GetQuery().AsNoTracking();
            if (catId > 0)
            {
                products = products.Where(l => l.ProductCategoryId == catId);
            }
            else if (parentId != null)
            {
                products = products.Where(a => a.ProductCategoryId == parentId || a.ProductCategory.ParentId == parentId);
            }
            if (!string.IsNullOrEmpty(name))
            {
                products = products.Where(l => l.Name.ToLower().Contains(name.ToLower()));
            }

            switch (sort)
            {
                case "sort-asc":
                    products = products.OrderBy(a => a.Sort);
                    break;
                case "sort-desc":
                    products = products.OrderByDescending(a => a.Sort);
                    break;
                case "date-asc":
                    products = products.OrderBy(a => a.CreateDate);
                    break;
                default:
                    products = products.OrderByDescending(a => a.CreateDate);
                    break;
            }
            var model = new ListProductViewModel
            {
                SelectCategories = new SelectList(ProductCategories.Where(a => a.ParentId == null), "Id", "CategoryName"),
                Products = products.ToPagedList(pageNumber, pageSize),
                CatId = catId,
                ParentId = parentId,
                Name = name,
                Sort = sort
            };
            if (parentId.HasValue)
            {

BinhTung/Views/ProductVcms/Product.cshtml
@model BinhTung.ViewModel.InsertProductViewModel
@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Thêm sản phẩm</h2>
<a class="btn quick-link" href="@Url.Action("ListProduct")"><i class="far fa-list mr-1"></i> Danh sách sản phẩm</a>
<div class="box_content">
    @using (Html.BeginForm("Product", "ProductVcms", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary(true)
        <table class="form_table">
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.CategoryId)</td>
                <td class="form_text">
                    <div class="row">
                        <div class="col-4">
                            @Html.DropDownListFor(model => model.ParentId, Model.ProductCategoryList, "Danh mục sản phẩm cha", new { @class = "form_control w300", onchange = "loadChildCategory(this.value)" })
                            @Html.ValidationMessageFor(model => model.ParentId)
                        </div>
                        <div class="col-4">
                            @Html.DropDownListFor(model => model.CategoryId, Model.ChildCategoryList, "Danh mục sản phẩm", new { @class = "form_control w300", id = "ChildCategoryId" })
                            @Html.ValidationMessageFor(model => model.CategoryId)
                        </div>
                        @*<div class="col-4">
                            @Html.EnumDropDownListFor(model => model.Product.ProductType, new { @class = "form_control w300" })
                        </div>*@
                    </div>
                </td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Name)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.Name)</td>
            </tr>
            @*<tr>
                    <td class="form_name">@Html.LabelFor(model => model.Product.Code)</td>
                    <td class="form_text">@Html.EditorFor(model => model.Product.Code)</td>
                </tr>*@
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.ListImage)</td>
                <td class="form_text">
                    <div class="alert alert-info">
                        <p class="btn btn-success fileinput-button">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>Chọn ảnh...</span>
                            <input type="file" id="fileupload" name="files[]" accept="image/*" multiple="" />
                        </p><br />
                        - Chọn ảnh để upload: (gif, png, jpg, jpeg < 4MB)<br />
                        - Ảnh đầu tiên sẽ là ảnh đại diện<br />
                    </div>
                    <div id="progress" class="progress">
                        <div class="progress-bar progress-bar-success"></div>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="form_name"></td>
                <td class="form_text">
                    <ul id="ListImages"></ul>
                </td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Description)</td>
                <td class="form_text">
                    @Html.EditorFor(model => model.Product.Description)
                    @Html.ValidationMessageFor(model => model.Product.Description)
                </td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Quantity)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.Quantity)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Body)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.Body)</td>
            </tr>
            @*<tr>
                    <td class="form_name">@Html.LabelFor(model => model.Product.Use)</td>
                    <td class="form_text">@Html.EditorFor(model => model.Product.Use)</td>
                </tr>*@
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Home)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.Home)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Active)</td>
                <td class="form_text">@Html.CheckBoxFor(model => model.Product.Active, new { @checked = "checked" })</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.Sort)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.Sort)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.TitleMeta)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.TitleMeta)</td>
            </tr>
            <tr>
                <td class="form_name">@Html.LabelFor(model => model.Product.DescriptionMeta)</td>
                <td class="form_text">@Html.EditorFor(model => model.Product.DescriptionMeta)</td>
            </tr>
            <tr>
                <td class="form_name"></td>
                <td class="form_text">
                    <input type="submit" class="btn quick-link" value="Thêm mới" />
                </td>
            </tr>
        </table>
    }
</div>
@section scripts{
    <script src="~/Scripts/jquery.maskMoney.min.js"></script>
    <script>
        $(function () {
            $(".input-number").maskMoney({
                precision: 0,
                thousands: ','
            });
        });
        $(function () {
            $("#ListImages").sortable();
            $("#ListImages").disableSelection();
        });
        var i = 1;
        $("#fileupload").fileupload({
            add: function (e, data) {
                var uploadErrors = [];
                var acceptFileTypes = /^image\/(gif|jpe?g|png)$/i;
                if (data.originalFiles[0]["type"].length && !acceptFileTypes.test(data.originalFiles[0]["type"])) {
                    uploadErrors.push("Chỉ chấp nhận định dạng jpeg, jpg, png, gif");
                }
                if (data.originalFiles[0]["size"] > 4000000) {
                    uploadErrors.push("Dung lượng ảnh lớn hơn 4MB");
                }
                var totalImg = $("#ListImages .thumb-img-box").length;
                if (totalImg >= 10) {
                    uploadErrors.push("Chỉ đăng tối đa 10 ảnh");
                }
                if (uploadErrors.length > 0) {
                    alert(uploadErrors.join("\n"));
                    return false;
                } else {
                    data.submit();
                }
                return true;
            },
            url: "/Uploader/Upload?folder=products&r=" + Math.random(),
            dataType: "json",
            done: function (e, data) {
                $.each(data.result.files, function (index, file) {
                    $('#ListImages').append('<li><input type="hidden" name="Pictures" value ="' + file.name + '" /><img src="/images/products/' + file.name + '?w=80&h=80"/><a href="javascript:;" id="' + i + '" onclick="delfile(' + i + ')"><img src="/content/admin/icon-delete.png" alt="" style="vertical-align:middle" /></a></li>');
                });
                i = i + 1;
                $("#progress").fadeOut(2000);
            },
            start: function () {
                $("#progress .progress-bar").css("width", "0");
                $("#progress").show();
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $("#progress .progress-bar").css("width", progress + "%");
            }
        }).prop('disabled', !$.support.fileInput).parent().addClass($.support.fileInput ? undefined : 'disabled');

        function delfile(divid) {
            if (confirm('Bạn có chắc xóa ảnh này?')) {
                $('#' + divid).parent().fadeOut().remove();
            }
        }

        function loadChildCategory(id) {
            $.getJSON("/ProductVcms/GetChildCategory", { parentId: id }, function (data) {
                var items = [];
                items.push("<option value>Hãy chọn danh mục</option>");
                $.each(data, function (key, val) {
                    items.push("<option value='" + val.Id + "'>" + val.CategoryName + "</option>");
                });
                $("#ChildCategoryId").html(items.join(""));
            });
        }
    </script>
}

BinhTung/Views/ProductVcms/ProductCategory.cshtml
@model BinhTung.Models.ProductCategory
@{
    ViewBag.Title = "Thêm danh mục";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Thêm mới danh mục</h2>
@if (ViewBag.ArticleCat == "success")
{
    <div id="AlertBox" class="alert alert-success"><strong>Thêm mới danh mục thành công</strong></div>
}
@if (ViewBag.ArticleCat == "update")
{
    <div id="AlertBox" class="alert alert-success"><strong>Cập nhật danh mục thành công</strong></div>
}
<a class="btn quick-link" id="create-cat" href="#list-cat"><i class="far fa-list mr-1"></i> Danh sách danh mục</a>
<div class="box_content">
    <div class="row">
        <div class="col-sm-12 col-lg-5">
            @using (Html.BeginForm("ProductCategory", "ProductVcms", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
                <table class="form_table form-table-cat">
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.ParentId)</td>
                        <td class="form_text">@Html.DropDownListFor(a => Model.ParentId, (SelectList)ViewBag.RootCats, "Danh mục cha", new { @class = "form_control w300" })</td>
                    </tr>
                    @*<tr>
                        <td class="form_name">@Html.LabelFor(a => Model.TypeShow)</td>
                        <td class="form_text">@Html.EnumDropDownListFor(a => Model.TypeShow, new { @class = "form_control w300" })</td>
                    </tr>*@
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.CategoryName)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.CategoryName)</td>
                    </tr>
                    @*<tr>
                            <td class="form_name">@Html.LabelFor(a => Model.Description)</td>
                            <td class="form_text">@Html.EditorFor(a => Model.Description)</td>
                        </tr>*@
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.Image)</td>
                        <td class="form_text">
                            <div class="alert alert-info">
                                <p class="btn" style="margin: 0 0 0 -15px; text-align: left;">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    <button class="btn-search" type="button" onclick="triggerImage()">Chọn ảnh</button>
                                    @Html.TextBoxFor(a => Model.Image, new { @class = "form-control hidden file-select", @type = "file" })
                                    @if (Model.Image != null)
                                    {
                                        <img id="thumb" style="width:200px;" src="/images/productCategory/@Model.Image" />
                                        <input type="hidden" name="oldfile" value="/images/productCategory/@Model.Image" />
                                    }
                                    else
                                    {
                                        <img id="thumb" style="width: 200px" src="" />
                                    }
                                </p><br />
                                - Chọn ảnh để upload: (gif, png, jpg, jpeg < 4MB)<br />
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.Url)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.Url)</td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.CategorySort)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.CategorySort)</td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.Special)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.Special)</td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.ShowHome)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.ShowHome)</td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.CategoryActive)</td>
                        <td class="form_text">@Html.CheckBoxFor(a => Model.CategoryActive, new { @checked = "checked" })</td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.TitleMeta)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.TitleMeta)</td>
                    </tr>
                    <tr>
                        <td class="form_name">@Html.LabelFor(a => Model.DescriptionMeta)</td>
                        <td class="form_text">@Html.EditorFor(a => Model.DescriptionMeta)</td>
                    </tr>
                    <tr>
                        <td class="form_name"></td>
                        <td class="form_text">
                            <input type="submit" class="btn quick-link" value="Thêm mới" />
                        </td>
                    </tr>
                </table>
            }
        </div>
        <div class="col-sm-12 col-lg-7">
            @Html.Action("ListCategory", "ProductVcms")
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#thumb').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
        $("#Image").change(function () {
            readURL(this);
        });
        function triggerImage() {
            $('.file-select').trigger('click');
        }
        function changeImage(event) {
            $('#image-name').html($('.file-select').val());
        }
    </script>
}