BinhTung/Controllers/ArticleController.cs
using BinhTung.DAL;
using BinhTung.Models;
using BinhTung.ViewModel;
using Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BinhTung.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        private IEnumerable<ArticleCategory> ArticleCategories => _unitOfWork.ArticleCategoryRepository.Get();

        #region ArticleCategory
        [ChildActionOnly]
        public ActionResult ListCategory()
        {
            var allcats = _unitOfWork.ArticleCategoryRepository.Get(orderBy: q => q.OrderBy(a => a.CategorySort));
            return PartialView(allcats);
        }
        public ActionResult ArticleCategory(string result = "")
        {
            ViewBag.ArticleCat = result;
            ViewBag.RootCats =
                new SelectList(
                    _unitOfWork.ArticleCategoryRepository.Get(a => a.ParentId == null,
                                                              q => q.OrderBy(a => a.CategorySort)), "Id", "CategoryName");
            var articleCat = new ArticleCategory();
            return View(articleCat);
        }
        [HttpPost]
        public ActionResult ArticleCategory(ArticleCategory category)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files["Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (file.ContentType != "image/jpeg" & file.ContentType != "image/png" && file.ContentType != "image/gif")
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg");
                    }
                    else
                    {
                        if (file.ContentLength > 4000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 4MB. Hãy thử lại");
                        }
                        else
                        {
                            var imgPath = "/images/articleCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = DateTime.Now.ToFileTimeUtc() + Path.GetExtension(file.FileName);

                            category.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                            var newImage = Image.FromStream(file.InputStream);
                            var fixSizeImage = HtmlHelpers.FixedSize(newImage, 600, 600, false);
                            HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);
                            //file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }
                category.Url = HtmlHelpers.ConvertToUnSign(null, category.Url ?? category.CategoryName);
                _unitOfWork.ArticleCategoryRepository.Insert(category);
                _unitOfWork.Save();
                return RedirectToAction("ArticleCategory", new { result = "success" });
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(l => l.ParentId == null, a => a.OrderBy(c => c.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        public ActionResult UpdateCategory(int catId = 0)
        {
            var category = _unitOfWork.ArticleCategoryRepository.GetById(catId);
            if (category == null)
            {
                return RedirectToAction("ArticleCategory");
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(l => l.ParentId == null, a => a.OrderBy(c => c.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost]
        public ActionResult UpdateCategory(ArticleCategory category, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files["Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (file.ContentType != "image/jpeg" & file.ContentType != "image/png" && file.ContentType != "image/gif")
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg");
                    }
                    else
                    {
                        if (file.ContentLength > 4000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 4MB. Hãy thử lại");
                        }
                        else
                        {
                            var imgPath = "/images/articleCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = DateTime.Now.ToFileTimeUtc() + Path.GetExtension(file.FileName);

                            if (System.IO.File.Exists(Server.MapPath("/images/articleCategory/" + category.Image)))
                            {
                                System.IO.File.Delete(Server.MapPath("/images/articleCategory/" + category.Image));
                            }
                            category.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                            var newImage = Image.FromStream(file.InputStream);
                            var fixSizeImage = HtmlHelpers.FixedSize(newImage, 600, 600, false);
                            HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);
                        }
                    }
                }
                else
                {
                    category.Image = fc["CurrentFile"];
                }
                category.Url = HtmlHelpers.ConvertToUnSign(null, category.Url ?? category.CategoryName);
                _unitOfWork.ArticleCategoryRepository.Update(category);
                _unitOfWork.Save();
                return RedirectToAction("ArticleCategory", new { result = "update" });
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(a => a.ParentId == null, q => q.OrderBy(a => a.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost]
        public bool DeleteCategory(int catId = 0)
        {
            var category = _unitOfWork.ArticleCategoryRepository.GetById(catId);
            if (category == null)
            {
                return false;
            }
            _unitOfWork.ArticleCategoryRepository.Delete(category);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateArticleCat(int sort = 1, bool active = false, bool menu = false, bool home = false, int articleCatId = 0)
        {
            var articleCat = _unitOfWork.ArticleCategoryRepository.GetById(articleCatId);
            if (articleCat == null)
            {
                return false;
            }
            articleCat.CategorySort = sort;
            articleCat.CategoryActive = active;
            articleCat.ShowMenu = menu;
            articleCat.ShowHome = home;

            _unitOfWork.Save();
            return true;
        }
        #endregion

        #region Article
        public ActionResult ListArticle(int? page, string name, int? catId, int? childId, string result = "")
        {
            ViewBag.Result = result;
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var article = _unitOfWork.ArticleRepository.Get(orderBy: l => l.OrderByDescending(a => a.Id));

            if (childId.HasValue)
            {
                article = article.Where(l => l.ArticleCategoryId == childId);
            }
            else if (catId.HasValue)
            {
                article = article.Where(l => l.ArticleCategoryId == catId || l.ArticleCategory.ParentId == catId);
            }
            if (!string.IsNullOrEmpty(name))
            {
                article = article.Where(l => l.Subject.ToLower().Contains(name.ToLower()));
            }
            var model = new ListArticleViewModel
            {
                SelectCategories = new SelectList(ArticleCategories.Where(a => a.ParentId == null), "Id", "CategoryName"),
                Articles = article.ToPagedList(pageNumber, pageSize),
                CatId = catId,
                ChildId = childId,
                Name = name
            };

            if (catId.HasValue)
            {
                model.ChildCategoryList =
                    new SelectList(ArticleCategories.Where(a => a.ParentId == catId), "Id", "CategoryName");
            }
            return View(model);
        }
        public ActionResult Article()
        {
            var model = new InsertArticleViewModel
            {
                Categories = ArticleCategories,
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Article(InsertArticleViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;
                var file = Request.Files["Article.Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif"))
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg");
                        isPost = false;
                    }
                    else
                    {

BinhTung/Controllers/BannerController.cs
using BinhTung.DAL;
using BinhTung.ViewModel;
using Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BinhTung.Controllers
{
    [Authorize]
    public class BannerController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        #region Banner
        public ActionResult ListBanner(int groupId = 0, string result = "")
        {
            ViewBag.Banner = result;
            var banners = _unitOfWork.BannerRepository.GetQuery(orderBy: q => q.OrderBy(a => a.GroupId).ThenBy(a => a.Sort));
            if (groupId > 0)
            {
                banners = banners.Where(a => a.GroupId == groupId);
            }
            var model = new ListBannerViewModel
            {
                Banners = banners
            };
            return View(model);
        }
        public ActionResult Banner()
        {
            var model = new BannerViewModel()
            {
                Banner = new Models.Banner() { Sort = 1, Active = true }
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Banner(BannerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files["Banner.Image"];
                if (file == null || file.ContentLength <= 0)
                {
                    ModelState.AddModelError("", @"Hãy chọn 1 hình ảnh.");
                    return View(model);
                }

                if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif|svg"))
                {
                    ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg, svg");
                    return View(model);
                }

                if (file.ContentLength > 4000 * 1024)
                {
                    ModelState.AddModelError("", @"Dung lượng lớn hơn 4MB. Hãy thử lại");
                    return View(model);
                }

                var imgPath = "/images/banners/" + DateTime.Now.ToString("yyyy/MM/dd");
                HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                var imgFileName = DateTime.Now.ToFileTimeUtc() + Path.GetExtension(file.FileName);

                model.Banner.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;
                file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));

                _unitOfWork.BannerRepository.Insert(model.Banner);
                _unitOfWork.Save();

                return RedirectToAction("ListBanner", new { result = "success" });
            }
            return View(model);
        }
        public ActionResult EditBanner(int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return RedirectToAction("ListBanner");
            }
            var model = new BannerViewModel
            {
                Banner = banner
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult EditBanner(BannerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;

                var banner = _unitOfWork.BannerRepository.GetById(model.Banner.Id);

                var file = Request.Files["Banner.Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif|svg"))
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg, svg");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 4000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 4MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/banners/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = DateTime.Now.ToFileTimeUtc() + Path.GetExtension(file.FileName);

                            banner.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }

                if (isPost)
                {
                    banner.GroupId = model.Banner.GroupId;
                    banner.BannerName = model.Banner.BannerName;
                    banner.Slogan = model.Banner.Slogan;
                    banner.Sort = model.Banner.Sort;
                    banner.Active = model.Banner.Active;
                    banner.Url = model.Banner.Url;
                    banner.Content = model.Banner.Content;
                    _unitOfWork.BannerRepository.Update(banner);
                    _unitOfWork.Save();

                    return RedirectToAction("ListBanner", new { result = "update" });
                }
            }
            return View(model);
        }
        [HttpPost]
        public bool DeleteBanner(int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return false;
            }
            HtmlHelpers.DeleteFile(Server.MapPath("/images/banners/" + banner.Image));
            _unitOfWork.BannerRepository.Delete(banner);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateBannerQuick(int sort = 1, bool active = false, int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return false;
            }
            banner.Sort = sort;
            banner.Active = active;

            _unitOfWork.Save();
            return true;
        }
        #endregion
        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

BinhTung/Views/Shared/_AdminLayout.cshtml
@using BinhTung.Models
@{
    var config = (ConfigSite)HttpContext.Current.Application["ConfigSite"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width" />*@
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.png">
    @Styles.Render("~/Content/admincss", "~/Content/themes/base/css")
    <link href="~/Scripts/multi-upload/jquery.fileupload.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
</head>
<body>
    <div id="responsive">
        <div class="app-header">
            <div class="app-header__logo">
                @*@if (config.Image != null)
                    {
                        <a href="@Url.Action("Index","Home")" target="_blank"><img class="logo-admin" src="@Path.Combine("/images/configs/", config.Image)" alt="logo" /></a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index","Home")" target="_blank"><img class="logo-admin" src="~/Content/images/logo-icon/logo.png" /></a>
                    }*@
                <a href="@Url.Action("Index","Vcms")"><img class="logo-admin" src="~/Content/images/logo-icon/logo.png" /></a>
                <a id="btn-show" onclick="myFunction()"><i class="fal fa-bars"></i><i class="fal fa-times"></i></a>
            </div>
            <div class="app-header__content">
                <div class="media mr-lg-5 mr-3 drop">
                    <img class="mr-3 avatar" src="~/Content/admin/icon_profile.png" />
                    <div class="media-body">
                        <h5 class="mb-0">@User.Identity.Name</h5>
                        Quản trị viên
                    </div>
                    <div class="content-drop">
                        <a href="@Url.Action("LogOut","Vcms")"><i class="fal fa-sign-out-alt pr-1"></i> Đăng xuất</a>
                        <a href="@Url.Action("ChangePassword","Vcms")"><i class="fal fa-low-vision mr-1"></i>Đổi mật khẩu</a>
                        <a href="@Url.Action("ConfigSite","Vcms")"><i class="fal fa-info-circle"></i> Thông tin chung</a>
                    </div>
                </div>
                <a id="help" class="drop" onclick="fbFunction()">
                    <i class="fas fa-user-headset"></i>
                    <div class="content-drop">Gửi yêu cầu cho chúng tôi</div>
                </a>
            </div>
        </div>
        <div id="left_menu_profile">
            <div class="left_menu_profile">
                <ul class="drop-bar">
                    <li data-id="5">
                        <a class="root expand mb-3" href="@Url.Action("Index","Vcms")">Tổng quan website</a>
                    </li>
                    <li data-id="0">
                        <a class="root"><span>Admin</span><i class="fas fa-caret-down"></i></a>
                        <div class="sub hidden">
                            <div>@Html.ActionLink("Đổi mật khẩu", "ChangePassword", "Vcms", null, new { @class = "text_link" })</div>
                            @*<div>@Html.ActionLink("Quản lý admin", "CreateAdmin", "Vcms", null, new { @class = "text_link" })</div>*@
                            <div>@Html.ActionLink("Thông tin chung", "ConfigSite", "Vcms", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Đăng xuất", "Logout", "Vcms", null, new { @class = "text_link" })</div>
                        </div>
                    </li>
                    @*<li data-id="1">
                            <a class="root"><span>Quản lý chính sách</span><i class="fas fa-caret-down"></i></a>
                            <div class="sub hidden">
                                <div>@Html.ActionLink("Thêm mới bài viết", "Support", "Article", null, new { @class = "text_link" })</div>
                                <div>@Html.ActionLink("Danh sách bài viết", "ListSupport", "Article", null, new { @class = "text_link" })</div>
                            </div>
                        </li>*@
                    <li data-id="2">
                        <a class="root"><span>Quản lý Bài viết</span><i class="fas fa-caret-down"></i></a>
                        <div class="sub hidden">
                            <div>@Html.ActionLink("Quản lý danh mục", "ArticleCategory", "Article", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Thêm mới bài viết", "Article", "Article", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Danh sách bài viết", "ListArticle", "Article", null, new { @class = "text_link" })</div>
                        </div>
                    </li>
                    <li data-id="3">
                        <a class="root"><span>Quản lý Sản phẩm</span><i class="fas fa-caret-down"></i></a>
                        <div class="sub hidden">
                            <div>@Html.ActionLink("Quản lý danh mục", "ProductCategory", "ProductVcms", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Thêm mới sản phẩm", "Product", "ProductVcms", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Danh sách sản phẩm", "ListProduct", "ProductVcms", null, new { @class = "text_link" })</div>
                        </div>
                    </li>
                    <li data-id="5">
                        <a class="root"><span>Quản lý phẩn hồi</span><i class="fas fa-caret-down"></i></a>
                        <div class="sub hidden">
                            <div class="first">@Html.ActionLink("Danh sách phản hồi", "ListFeedback", "Contact", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Thêm phản hồi", "Feedback", "Contact", null, new { @class = "text_link" })</div>
                        </div>
                    </li>
                    <li data-id="7">
                        <a class="root"><span>Quản lý Quảng cáo</span><i class="fas fa-caret-down"></i></a>
                        <div class="sub hidden">
                            <div>@Html.ActionLink("Thêm mới quảng cáo", "Banner", "Banner", null, new { @class = "text_link" })</div>
                            <div>@Html.ActionLink("Danh sách quảng cáo", "ListBanner", "Banner", null, new { @class = "text_link" })</div>
                        </div>
                    </li>
                    <li data-id="9">
                        <a class="root"><span>Quản lý Liên hệ</span><i class="fas fa-caret-down"></i></a>
                        <div class="sub hidden">
                            <div>@Html.ActionLink("Danh sách liên hệ", "ListContact", "Contact", null, new { @class = "text_link" })</div>
                            @*<div>@Html.ActionLink("Danh sách email đăng ký", "ListSubscribe", "Contact", null, new { @class = "text_link" })</div>*@
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div id="content_center_right">
            <div class="content_center_right">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/bundles/jqueryui")
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.3.0.min.js"></script>
    <script src="~/Scripts/multi-upload/jquery.iframe-transport.js"></script>
    <script src="~/Scripts/multi-upload/jquery.fileupload.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery.toast.js"></script>
    <script src="~/Scripts/ckeditor/adapters/jquery.js"></script>
    <script src="~/Scripts/jquery.cookie.js"></script>
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <script src="~/Scripts/scriptAdmin.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

BinhTung/Views/Shared/_ItemProduct.cshtml
@model BinhTung.Models.Product
<div class="box">
    <a href="@Url.Action("ProductDetail", new { url = Model.Url })" class="box__name truncate-h" data-line="1">@Model.Name</a>
    <a href="@Url.Action("ProductDetail", new { url = Model.Url })">
        @if (Model.ListImage != null)
        {
            <div class="item-img">
                <img class="img-fluid img img--product" src="@Path.Combine("/images/products/", Model.ListImage.Split(',')[0])" alt="@Model.Name" />
            </div>
        }
    </a>
</div>

BinhTung/Views/Shared/_Layout.cshtml
@using BinhTung.Models
@{
    var config = (ConfigSite)HttpContext.Current.Application["ConfigSite"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <meta name="description" content="@Html.Raw(ViewBag.Description)" />
    <meta name="robots" content="index,follow" />
    <link rel="canonical" href="@ViewBag.Canonical" />
    <link rel="shortcut icon" href="~/favicon.png">
    <meta property="og:locale" content="vi_VN">
    <meta property="og:type" content="website">
    <meta property="og:title" content="@Html.Raw(ViewBag.Title)">
    <meta property="og:description" content="@Html.Raw(ViewBag.Description)">
    <meta property="og:url" content="@ViewBag.Canonical">
    <meta property="og:site_name" content="@Html.Raw(ViewBag.Title)">
    <meta property="og:image" content="@(ViewBag.ImagShare ?? "https://"+Request.Url?.Host+"/content/images/logo.png")" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @if (config.GoogleAnalytics != null)
    {
        @Html.Raw(config.GoogleAnalytics)
    }
</head>
<body>
    @Html.Action("Header", "Home")
    @RenderBody()
    @Html.Action("Footer", "Home")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v8.0" nonce="di1pgAbX"></script>
    @if (config.LiveChat != null)
    {
        @Html.Raw(config.LiveChat)
    }
</body>
</html>